Category.create()
Category.create(name: "Ruby")
Category.create(name: "Python")
Category.create(name: "Javascript")
Category.create(name: "HTML")
Category.create(name: "C++")
Category.create(name: "CSS")
Category.create(name: "Binary")
Category.create(name: "Robot Tinder")
Category.create(name: "Random")
